# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-08-31 19:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coupons', '0008_coupon_code_citext'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coupon',
            name='type',
            field=models.CharField(choices=[('monetary', 'Money based coupon'), ('percentage', 'Percentage discount'), ('seats', 'TripSeat based discount')], max_length=20, verbose_name='Type'),
        ),
    ]
