# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-09-20 18:33
from __future__ import unicode_literals

from django.db import migrations, models


def populate_redeem_count(apps, schema_editor):
    """
    Populate any existing CouponUser objects with correct redeem_counts
    """
    CouponUser = apps.get_model('coupons', 'CouponUser')

    redeemed_coupon_users = CouponUser.objects.filter(
        last_redeemed_at__isnull=False
    )
    for coupon_user in redeemed_coupon_users:
        coupon_user.redeem_count = 1
        coupon_user.save(update_fields=('redeem_count',))


class Migration(migrations.Migration):

    dependencies = [
        ('coupons', '0009_coupon_seat_type'),
    ]

    operations = [
        migrations.RenameField(
            model_name='couponuser',
            old_name='redeemed_at',
            new_name='last_redeemed_at',
        ),
        migrations.AlterField(
            model_name='couponuser',
            name='last_redeemed_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Last redeemed at'),
        ),
        migrations.AddField(
            model_name='coupon',
            name='limit_per_user',
            field=models.PositiveIntegerField(default=1, verbose_name='Coupon redeem limit per User'),
        ),
        migrations.AddField(
            model_name='couponuser',
            name='redeem_count',
            field=models.PositiveIntegerField(default=0, verbose_name='Redeem count'),
        ),
        migrations.RunPython(populate_redeem_count)
    ]
